<a href="https://colab.research.google.com/github/sushant758/ML-Exercises/blob/main/Missing_values_KNN_Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [71]:
df =pd.read_csv('train (1).csv')[['Age','Pclass','Fare','Survived']]

In [72]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [73]:
df.shape

(891, 4)

In [74]:
df.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

In [75]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [76]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [77]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [78]:
X_train.shape

(712, 3)

In [79]:
X_test.shape

(179, 3)

In [80]:
y_train.shape

(712,)

In [81]:
y_test.shape

(179,)

In [82]:
X_train.head()

      Age  Pclass     Fare
331  45.5       1  28.5000
733  23.0       2  13.0000
382  32.0       3   7.9250
704  26.0       3   7.8542
813   6.0       3  31.2750

In [83]:
knn = KNNImputer(n_neighbors=3 , weights='uniform') # or 'uniform' or 'distance'

X_train_trf = knn.fit_transform(X_train)
X_test_trf =  knn.transform(X_test)

In [84]:
# Here i  dont have applied knnimputer on y_train or y_test

In [85]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

LogisticRegression()

In [86]:
y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7430167597765364

In [88]:
# getting accurancy weights='distance' = 0.7374301675977654
# getting accurancy weights='uniform' = 0.7430167597765364

In [89]:
# Comparision with Simple Imputer --> mean

In [90]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [91]:
lr = LogisticRegression()

lr.fit(X_train_trf2 , y_train)

LogisticRegression()

In [92]:
y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_test , y_pred2)

0.7374301675977654