<a href="https://colab.research.google.com/github/sushant758/ML-Exercises/blob/main/ML5_V4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Iris.csv')

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('Species',axis=1)
y = df['Species']

In [ ]:
# when you will use cross validation , you dont
# have to use train test split

# But here, now  i am using train test split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.3 , random_state=42)

In [ ]:
# using KNN
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors = 13)

In [ ]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.score(X_test,y_test)

1.0

In [ ]:
# now it means that model is getting overfit

# SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm = SVC(gamma='auto')

In [ ]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test,y_test)

1.0

# Now lets use grid search CV

In [ ]:
# this can reduce the overfitting of our model

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# now perform hyperparameter tunning / create grids

In [ ]:
classifier = GridSearchCV((model_svm),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [ ]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.0034339 , 0.0023612 , 0.00347228, 0.00231209, 0.00341725,
        0.00231786]),
 'std_fit_time': array([1.62627856e-04, 7.14074749e-05, 4.22834779e-04, 7.34927503e-05,
        3.56160396e-04, 2.17766231e-04]),
 'mean_score_time': array([0.00231495, 0.00185113, 0.00199642, 0.00182219, 0.0023273 ,
        0.00176644]),
 'std_score_time': array([3.96876199e-04, 1.23528382e-04, 5.41638738e-05, 1.44591416e-04,
        4.49982831e-04, 9.37288905e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.95238095, 1.        , 0.95238095, 1.        , 0.95238095,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split3_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.99047619, 1.        , 0.99047619, 1.        , 0.99047619,
        1.        ]),
 'std_test_score': array([0.01904762, 0.        , 0.01904762, 0.        , 0.01904762,
        0.        ]),
 'rank_test_score': array([4, 1, 4, 1, 4, 1], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003434,0.000163,0.002315,0.000397,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.952381,1.0,1.0,1.0,1.0,0.990476,0.019048,4
1,0.002361,0.000071,0.001851,0.000124,1,linear,"{'C': 1, 'kernel': 'linear'}",1.000000,1.0,1.0,1.0,1.0,1.000000,0.000000,1
2,0.003472,0.000423,0.001996,0.000054,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.952381,1.0,1.0,1.0,1.0,0.990476,0.019048,4
3,0.002312,0.000073,0.001822,0.000145,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,1.0,1.0,1.0,1.000000,0.000000,1
4,0.003417,0.000356,0.002327,0.000450,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.952381,1.0,1.0,1.0,1.0,0.990476,0.019048,4
5,0.002318,0.000218,0.001766,0.000094,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,1.0,1.0,1.0,1.000000,0.000000,1

In [ ]:
results[['param_C' , 'param_kernel' , 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.990476
1        1       linear         1.000000
2       10          rbf         0.990476
3       10       linear         1.000000
4       20          rbf         0.990476
5       20       linear         1.000000